"""init db

Revision ID: 6ae022866637
Revises: 
Create Date: 2023-04-27 14:59:15.076647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae022866637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('portion_size', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_created'), 'food', ['created'], unique=False)
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('output_time', sa.DateTime(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_dispensed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_dispensed', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('trigger', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('tiemtable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['tiemtable_id'], ['timetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_dispensed')
    op.drop_table('timetable')
    op.drop_index(op.f('ix_food_created'), table_name='food')
    op.drop_table('food')
    # ### end Alembic commands ###
